version: "3.2"

services:
    app:
        build: .
        command: runserver 0.0.0.0:8000
        links:
            - db
        ports:
            - '8000:8000'
        environment:
            - DB_HOST=db
            - DB_PORT=3306

    db:
        image: mariadb
        volumes:
            - 'data:/var/lib/mysql'
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=hogefuga
            - MYSQL_DATABASE=regisys

volumes:
    data:
        driver: local
